name: Deploy Valaxy to GitHub Pages

on:
  push:
    branches:
      - main  # 监听 main 分支的 push 事件

permissions:
  contents: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # Valaxy 推荐使用 Node.js 18

      - name: Install Dependencies
        run: npm install

      - name: Build Site
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
